name: super_commercial_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.6.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  url_launcher: ^6.3.2
  mobile_scanner: ^6.0.4
  permission_handler: ^11.3.1
  barcode_widget: ^2.0.4
  printing: ^5.13.1
  pdf: ^3.11.2
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  intl: ^0.20.2
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
